### ISSUE TITLE
Cardinal

### ISSUE THREAD

**Issue by prititayade24** [ReactiveSets/toubkal#5]
Please,  Support the demonstrative apps on it, so we'll better understand & exercise this npm. THANK YOU.

**Comment by uiteoi** [comment]
Sorry but I don't understand what this issue is really about. What do you mean by Cardinal?

What kind of support are you expecting? On what demonstrative app?

**Comment by prititayade24** [comment]
As an aspirant I'm so curious about implementing codes, that's why I emphasised it as indisputable or It's so required. Sorry for inconvenience.

**Comment by uiteoi** [comment]
I cannot help you if you don't explain what you need.

**Comment by uiteoi** [comment]
Closing as their is no further response to allow to understand what's desired

**Comment by prititayade24** [comment]
I got solution what I wanted. Thank you for your active support.
